image:
  repository: ghcr.io/mixermachine/alexa-feed-json-generator
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 6565
  targetPort: 6565

ingress:
  enabled: true
  className: "traefik"
  clusterIssuer: "letsencrypt-prod"
  host: "alexa-feed.9d3.de"
  path: /
  pathType: Prefix
  tls: true

persistence:
  enabled: true
  existingClaim: alexa-feed-files
  mountPath: /app/files
  size: 1Gi
  storageClass: "local-path"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

env: []
